export const SLIDES = [
  {
    id: 'cover', label: 'BE4T',
    eyebrow: 'REAL WORLD ASSETS · MÚSICA',
    title: 'BE<accent>4</accent>T',
    subtitle: 'La primera plataforma de Fan Equity Musical. Donde los fans no solo escuchan — son dueños.',
    type: 'cover',
  },
  {
    id: 'problem', label: 'El Problema',
    eyebrow: 'THE GAP',
    title: 'El puente roto entre artista y fan',
    type: 'problem',
    analogy: {
      icon: '⚽',
      title: 'Lección de los Fan Tokens del Fútbol',
      text: 'PSG, Juventus y Barça lanzaron Fan Tokens y generaron $150M+ en liquidez. La música tiene 10x más base de fans global — y aún no tiene este modelo.',
    },
    cols: [
      {
        heading: 'Para el Artista',
        color: '#ff4d6d',
        points: [
          ['$0.004/stream', 'Un hit de 10M streams = $40K antes de comisiones. Sin capital para el próximo lanzamiento.'],
          ['Data secuestrada', 'Spotify es dueño del fan. El artista no sabe quién es su top 1% más valioso.'],
          ['Fidelidad sin recompensa', 'El fan devoto tiene exactamente los mismos derechos que quien escuchó una vez.'],
        ],
      },
      {
        heading: 'La Dualidad de los Tokens',
        color: '#00f0ff',
        points: [
          ['Equity Funcional', 'Derechos sobre ingresos de regalías. El fan gana cuando la canción crece.'],
          ['Utility Real', 'Boletas VIP, merch exclusivo, contenido behind-the-scenes, meet & greet.'],
          ['Fidelidad Extrema', 'Cuando el fan tiene "skin in the game", su compromiso emocional se convierte en compromiso económico.'],
        ],
      },
    ],
  },
  {
    id: 'loop', label: 'El Loop',
    eyebrow: 'THE GAME CHANGER',
    title: 'El Loop Virtuoso BE4T',
    subtitle: 'Un sistema de incentivos donde el éxito del artista y el fan está matemáticamente alineado.',
    type: 'loop',
    steps: [
      { icon: '💸', label: 'Fan compra Token', color: '#00f0ff', sub: 'Inversión desde $10 USD' },
      { icon: '🤝', label: 'Fan se vuelve Socio', color: '#a855f7', sub: 'Equity + Perks exclusivos' },
      { icon: '📣', label: 'Promoción Orgánica', color: '#facc15', sub: 'Incentivo real para hacer crecer streams' },
      { icon: '📈', label: 'Regalías suben', color: '#4ade80', sub: 'Más streams = más revenue' },
      { icon: '🔄', label: 'Fan y Artista ganan', color: '#00f0ff', sub: 'El loop se repite y escala' },
    ],
    benefits: [
      { icon: '📣', title: 'Marketing orgánico gratuito', desc: 'Tu comunidad tiene incentivo económico real para promoverte.' },
      { icon: '🛡️', title: 'Ruido mediático de vanguardia', desc: 'Ser el primer artista con Fan Tokens en tu género es PR masivo.' },
      { icon: '💎', title: 'Fidelidad a prueba de cancelas', desc: 'Los fans-inversores no se van; son embajadores de largo plazo.' },
    ],
  },
  {
    id: 'market', label: 'Mercado',
    eyebrow: 'TAMAÑO DEL MERCADO',
    title: 'Un mercado masivo y mal servido',
    type: 'market',
    stats: [
      { label: 'TAM — Mercado Global de Música', value: '$26.2B', pct: '100%', sub: 'Ingresos globales de la industria musical 2024 (IFPI)', color: '#00f0ff' },
      { label: 'SAM — Música Tokenizable LATAM + España', value: '$3.4B', pct: '~13% del TAM', sub: 'Regalías anuales en mercados hispanos con alta adopción digital', color: '#a855f7' },
      { label: 'SOM — Objetivo Año 3 BE4T', value: '$48M', pct: '1.4% del SAM', sub: 'Capturando 500 tracks activos y 25K inversores. Altamente conservador.', color: '#4ade80' },
    ],
    insight: 'La tokenización de activos reales (RWA) alcanzó $5B en 2024 y proyecta $16T para 2030 (BCG). BE4T está posicionado exactamente en esta intersección.',
  },
  {
    id: 'valuation', label: 'Valoración',
    eyebrow: 'VALUATION FRAMEWORK',
    title: 'La valoración no es al azar',
    subtitle: 'Usamos un framework de datos en tiempo real para calcular el valor justo de cada activo musical.',
    type: 'valuation',
    pillars: [
      { icon: '⚡', name: 'Streaming Velocity', color: '#00f0ff', desc: 'Velocidad de crecimiento de streams en los últimos 90 días. Detecta momentum antes que el mercado.' },
      { icon: '📊', name: 'Historical Consistency', color: '#a855f7', desc: 'Estabilidad de ingresos en los últimos 24 meses. Filtra hits de una sola vez vs catálogos perennes.' },
      { icon: '🎵', name: 'TikTok Engagement', color: '#facc15', desc: 'Virality index en TikTok/Reels. Predictor #1 de crecimiento de streams en los próximos 6 meses.' },
    ],
    example: {
      title: 'Ejemplo de Ticket Real',
      rows: [
        ['Valoración total de la canción', '$25,000 USD'],
        ['Ticket del 1% de participación', '$250 USD'],
        ['Revenue anual del 1% (APY 14%)', '$35 USD / año'],
        ['Break-even estimado del inversor', '~7 años + plus-value de reventa'],
      ],
    },
  },
  {
    id: 'secondary', label: 'Mercado Sec.',
    eyebrow: 'MERCADO SECUNDARIO P2P',
    title: 'El fan no está atrapado',
    subtitle: 'Liquidez total: los tokens se pueden revender entre fans en el mercado secundario. El artista gana royalties perpetuos en cada reventa.',
    type: 'secondary',
    flow: [
      { icon: '🧑', label: 'Fan A compra 100 tokens\na $2.50 c/u', color: '#00f0ff' },
      { icon: '📈', label: 'El artista crece.\nTokens valen $4.00 c/u', color: '#4ade80' },
      { icon: '🔄', label: 'Fan A vende a Fan B\nen el mercado P2P', color: '#a855f7' },
      { icon: '💰', label: 'Fan A gana $150.\nArtista recibe 5%\nde royalty perpetuo.', color: '#facc15' },
    ],
    metrics: [
      { label: 'Royalty del artista en cada reventa', value: '5%', color: '#facc15' },
      { label: 'Comisión de plataforma (BE4T)', value: '1.5%', color: '#00f0ff' },
      { label: 'Liquidez disponible para el fan', value: '24/7', color: '#4ade80' },
    ],
  },
  {
    id: 'features', label: 'Producto',
    eyebrow: 'PRODUCTO ACTUAL',
    title: 'Funcionalidades en Producción Hoy',
    type: 'features',
    list: [
      { icon: '🎧', title: 'Marketplace de Activos', desc: 'Catálogo de canciones tokenizadas con métricas en tiempo real (Spotify, YouTube, TikTok).' },
      { icon: '💼', title: 'Portfolio de Inversión', desc: 'Dashboard personalizado con ROI acumulado, regalías recibidas y valor del portafolio.' },
      { icon: '🔐', title: 'Bóveda de Perks (Gamification)', desc: 'Sistema FAN → SOCIO → VIP. Más tokens = más exclusividad y beneficios reales.' },
      { icon: '📱', title: 'Compra sin fricción', desc: 'Acceso con Google/Email. Sin wallet previa. Pago con USDC via Thirdweb Pay.' },
      { icon: '🔗', title: 'Smart Contracts Auditados', desc: 'ERC-1155 en Base L2. Gas mínimo, velocidad máxima.' },
      { icon: '📊', title: 'Métricas Live de Artistas', desc: 'APIs certificadas Spotify, YouTube, TikTok para valoración dinámica en tiempo real.' },
    ],
  },
  {
    id: 'infra-now', label: 'Infra Actual',
    eyebrow: 'INFRAESTRUCTURA HOY',
    title: 'Stack de Producción',
    type: 'infra',
    layers: [
      { name: 'Frontend', color: '#00f0ff', items: ['React + Vite', 'Vercel Edge Network', 'i18n ES/EN', 'Responsive PWA'] },
      { name: 'Auth & Wallet', color: '#a855f7', items: ['Thirdweb Social Login', 'Google + Email OTP', 'ERC-4337 Smart Wallets', 'Supabase Auth'] },
      { name: 'Blockchain', color: '#facc15', items: ['Base L2 (Sepolia + Mainnet)', 'ERC-1155 Vault Contract', 'USDC como moneda', 'On-chain yield'] },
      { name: 'Backend / Data', color: '#4ade80', items: ['Supabase (PostgreSQL)', 'user_investments table', 'Spotify + YouTube APIs', 'Vercel Serverless'] },
    ],
  },
  {
    id: 'legal', label: 'Legal & RWA',
    eyebrow: 'COMPLIANCE & JURISDICCIÓN',
    title: 'Estructura Legal RWA',
    type: 'legal',
    status: { label: '⚠️ Estado Actual', text: 'Pendiente de permisos y cumplimiento normativo. En proceso activo de estructuración legal.', color: '#facc15' },
    jurisdiction: {
      flag: '🇸🇻',
      country: 'El Salvador',
      law: 'Ley de Emisión de Activos Digitales (LEAD)',
      target: 'PSAD — Proveedor de Servicios de Activos Digitales',
      color: '#00f0ff',
      why: 'El Salvador es la jurisdicción más avanzada de LATAM en regulación de activos digitales. La LEAD ofrece un marco claro, predecible y amigable para RWA musicales.',
    },
    pillars: [
      { icon: '📄', title: 'SPV por Activo', desc: 'Cada canción tokenizada está respaldada por un vehículo de propósito especial (SPV) con acuerdo legal firmado con el titular de derechos.' },
      { icon: '🔒', title: 'KYC/AML Integrado', desc: 'Sumsub para verificación de identidad de inversores. Cumplimiento FATF en todas las jurisdicciones.' },
      { icon: '🌍', title: 'Hoja de Ruta MiCA', desc: 'Alineados con el marco regulatorio europeo MiCA para expansión a España y la Unión Europea en 2027.' },
    ],
  },
  {
    id: 'roadmap', label: 'Roadmap',
    eyebrow: 'INFRAESTRUCTURA FUTURA',
    title: 'Roadmap de Escalabilidad',
    type: 'roadmap',
    phases: [
      { phase: 'Q3 2026', name: 'Producto Completo', color: '#00f0ff', items: ['Mercado Secundario P2P en vivo', 'Distribución auto de regalías on-chain', 'KYC/AML integrado (Sumsub)', 'App móvil iOS + Android'] },
      { phase: 'Q4 2026', name: 'Escala LATAM', color: '#a855f7', items: ['100 tracks activos / 3 sellos firmados', 'White-label para distribuidoras', 'Licencia PSAD El Salvador', 'Cumplimiento MiCA (Europa)'] },
      { phase: '2027+', name: 'Liderazgo Global', color: '#facc15', items: ['500+ tracks / $10M tokenizados', 'DAO de Gobernanza token BE4T', 'Integración con majors (Universal, Sony)', 'Brasil, México, España'] },
    ],
  },
  {
    id: 'cta', label: 'Contacto',
    eyebrow: 'ÚNETE AL MOVIMIENTO',
    title: 'Validemos el próximo hit juntos.',
    subtitle: 'Buscamos $500K Seed para cerrar el producto, firmar los primeros 10 artistas y obtener la licencia PSAD en Q3 2026.',
    type: 'cta',
    buttons: [
      { label: 'Ver Demo Interactiva', url: 'https://be4t-mvp.vercel.app/', primary: true, icon: '🎮' },
      { label: 'Acceso App Real (Lista de Espera)', url: 'https://charged-satellite-three.vercel.app/', primary: false, icon: '🚀' },
    ],
    contacts: [
      { label: 'Email', val: 'hola@be4t.com' },
      { label: 'Deck', val: 'charged-satellite-three.vercel.app/pitch' },
      { label: 'LinkedIn', val: '/company/be4t' },
    ],
  },
];
